In [1]:
# gradient descent model implement
# 기울기가 가리키는 쪽은 각 장소에서 함수의 출력 값을 가장 크게 줄이는 방향!!!!

In [5]:
def numerical_gradient(f, x):
    h = 1e-4   # 0.0001
    grad = np.zeros_like(x)  # x와 형상이 같고, 원소가 모두 0인 배열을 생성

    for idx in range(x.size):
        tmp_val = x[idx]

    # f(x+h) 계산
    x[idx] = tmp_val + h
    fxh1 = f(x)

    # f(x-h) 계산
    x[idx] = tmp_val - h
    fxh2 = f(x)

    grad[idx] = (fxh1 - fxh2) / (2*h)
    x[idx] = tmp_val   # 값 복원

    return grad

In [6]:
# f: 최적화하려는 함수
# init_x: initial value
# lr: learning rate
# step_num: 경사법에 따른 반복 횟수

# grad: gradient

In [7]:
def gradient_descent(f, init_x, lr = 0.01, step_num = 100):   # 함수의 기울기 구하기
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
    return x

In [8]:
# gradient descent 방법으로 f(x0, x1) = x0^2 + x1^2 의 minimum value 를 구해라.

In [9]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [16]:
# initial value를 (-3.0, 4.0) 으로 설정하고, 경사법을 이용해서 minimum value를 탐색한다.

In [14]:
import numpy as np

In [15]:
# initial value의 최종 결과값을 보면, 거의 (0, 0)에 가까운 결과를 얻는다.

init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x = init_x, lr=0.1, step_num = 100)

array([-3.00000000e+00,  8.14011969e-10])

In [17]:
# learning rate 너무 크거나 작을 때: 좋은 결과를 얻을 수 없다.

In [18]:
# learning rate -> 너무 클 때!

In [19]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x = init_x, lr=10, step_num = 100)  # 값이 0에 가까워지지 않음(격차가 큼)

array([-3.00000000e+00, -1.26893162e+12])

In [20]:
# learning rate -> 너무 작을 때!

In [21]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x = init_x, lr=1e-10, step_num = 100)  # 값이 0에 가까워지지 않음(격차가 큼)

array([-3.        ,  3.99999992])